### ISSUE TITLE
What's the license on this?

### ISSUE THREAD

**Issue by alexmv** [cstrahan/go-watchman#1]
Heya,

I'd love to use this as the base for a faster version of [`fsmonitor-watchman`](https://github.com/git/git/blob/master/templates/hooks--fsmonitor-watchman.sample), which can be used to accelerate operations in large git repositories.

Can you provide a (ideally GPLv2-compatible) LICENSE file for this?

Relatedly, do you have any interest in pull requests to fix up some minor bugs?

**Comment by cstrahan** [comment]
I'm thinking dual MIT and Apache v2.

> Can you provide a (ideally GPLv2-compatible) LICENSE file for this?

Would my aforementioned licensing scheme work for your purposes?

> Relatedly, do you have any interest in pull requests to fix up some minor bugs?

Absolutely!

**Comment by alexmv** [comment]
Dual MIT/Apache sounds great to me.

I'll send along some pull requests as soon as the license lands.

**Comment by cstrahan** [comment]
> I'll send along some pull requests as soon as the license lands.

Done :)

**Comment by cstrahan** [comment]
Like a complete goof, I accidentally checked in a binary way back when I first slapped this code together. As far as I know, no one is using this yet, so I think I'm going to rebase and remove the file while the damage would be minimal -- just a heads up.

**Comment by cstrahan** [comment]
Alright, done with the rebase, so I'll go ahead and close this issue. Looking forward to any PRs and seeing what you do with this!
